@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjA0OTA2NzkxLCJleHAiOjE2MDc0OTg3OTF9.6tC7S_aK-dP7FDDLA4UbfPAQR4XqEGn3ttZkuOfqS-w

GET http://localhost:1337/events
Authorization: Bearer {{token}}

###

GET http://localhost:1337/events/1
Authorization: Bearer {{token}}

###

GET http://localhost:1337/events?timeline.id=3
Authorization: Bearer {{token}}

###

POST http://localhost:1337/events
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Semester",
  "description": "Nu åker vi!!",
  "timeline": "1"
}

###

PUT http://localhost:1337/events/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "new title",
  "description": "new description"
}

###

DELETE http://localhost:1337/events/1
Authorization: Bearer {{token}}
Content-Type: application/json