@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNTk4MzQ1MDU1LCJleHAiOjE2MDA5MzcwNTV9.4MC1v-lGQzUGOjpwcfeoNcmayx2UB5g3KovikSHpzDk

GET http://localhost:1337/events
Authorization: Bearer {{token}}

###

GET http://localhost:1337/events/1
Authorization: Bearer {{token}}

###

GET http://localhost:1337/events?timeline.id=3
Authorization: Bearer {{token}}

###

POST http://localhost:1337/events
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Semester",
  "description": "Nu åker vi!!",
  "timeline": "245"
}

###

PUT http://localhost:1337/events/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "new title",
  "description": "new description"
}

###

DELETE http://localhost:1337/events/1
Authorization: Bearer {{token}}
Content-Type: application/json