@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNTk1MjI4MDczLCJleHAiOjE1OTc4MjAwNzN9.NYyCjJ5HxOI_X731mOoq-wDAnqxiZ8H2rW1V3RwdQTk

###

GET http://localhost:1337/timelines
Authorization: Bearer {{token}}

###

GET http://localhost:1337/timelines/1
Authorization: Bearer {{token}}

###

PUT http://localhost:1337/timelines/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Kalles linje",
  "description": "En riktigt spännande historia!"
}


###

GET http://localhost:1337/timelines/?user.id=2
Authorization: Bearer {{token}}

###

GET http://localhost:1337/events
Authorization: Bearer {{token}}

###

GET http://localhost:1337/events/5
Authorization: Bearer {{token}}

###

PUT http://localhost:1337/events/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "new title",
  "description": "new description"
}

###

GET http://localhost:1337/events?timeline.id=3
Authorization: Bearer {{token}}

###

GET http://localhost:1337/users
Authorization: Bearer {{token}}

###

GET http://localhost:1337/users/1
Authorization: Bearer {{token}}

