@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNTk4MzQ1MDU1LCJleHAiOjE2MDA5MzcwNTV9.4MC1v-lGQzUGOjpwcfeoNcmayx2UB5g3KovikSHpzDk

###

GET http://localhost:1337/timelines
Authorization: Bearer {{token}}

###

GET http://localhost:1337/timelines/2
Authorization: Bearer {{token}}

###

POST http://localhost:1337/timelines
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Hej3",
  "description": "En riktigt spännande historia!",
  "events": [],
  "user": 1
}

###

PUT http://localhost:1337/timelines/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Kalles linje",
  "description": "En riktigt spännande historia!"
}

###

DELETE http://localhost:1337/timelines/3
Authorization: Bearer {{token}}

###

GET http://localhost:1337/timelines/?user.id=2
Authorization: Bearer {{token}}
###