@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNTk3NzkxMzczLCJleHAiOjE2MDAzODMzNzN9.CsfKYDG1rHsBLbh8KxX3SBL9Zj2w0AcCDRzNRtC9pts

###

GET http://localhost:1337/timelines
Authorization: Bearer {{token}}

###

GET http://localhost:1337/timelines/2
Authorization: Bearer {{token}}

###

POST http://localhost:1337/timelines
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Hej new",
  "description": "En riktigt spännande historia!",
  "events": [],
  "user": 2
}

###

PUT http://localhost:1337/timelines/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Kalles linje",
  "description": "En riktigt spännande historia!"
}

###

DELETE http://localhost:1337/timelines/3
Authorization: Bearer {{token}}

###

GET http://localhost:1337/timelines/?user.id=2
Authorization: Bearer {{token}}
###