@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjA0OTA2NzkxLCJleHAiOjE2MDc0OTg3OTF9.6tC7S_aK-dP7FDDLA4UbfPAQR4XqEGn3ttZkuOfqS-w

POST http://192.168.1.121:1337/auth/local

{
  "identifier": "zetajaz@gmail.com",
  "password": "Abc123!"
}

###

GET http://localhost:1337/users
Authorization: Bearer {{token}}

###

GET http://localhost:1337/users/1
Authorization: Bearer {{token}}

